version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout

      - run:
          name: Restore & Build API
          command: make build-project

      - run:
          name: Run Tests
          command: make run-tests